title: My GitHub Pages Site
description: >- # Describes your site.
  This is an example site powered by GitHub Pages and Jekyll.
theme: jekyll-theme-slate # This is one of GitHub Pages' supported themes.
